#	$Id: Makefile,v 1.2 2004/03/28 02:45:09 henry Exp $

include ../Makefile.config

EXEC = visiteur

IDL        = visiteur

MODULES    = formule
MLINCDIRS =

LIBRARIES  = 
CLIBS      = 

MLOCLASS   = Formule Visiteur VisiteurTS
MLOCBCLASS = Formule Visiteur

CLASS      = $(addprefix fr/upmc/infop6/mlo/,$(MLOCLASS))
CBCLASS    = $(addprefix fr/upmc/infop6/mlo/,$(MLOCBCLASS))

include $(OJACAREDIR)/Makefile.include
