#	$Id: Makefile.config,v 1.2 2004/03/19 20:42:56 henry Exp $

# Adjust to your O'Caml installation


OCAMLFIND = ocamlfind
OCAMLC = ${OCAMLFIND} ocamlc
OCAMLOPT = ${OCAMLFIND} ocamlopt
OCAMLMKLIB = ocamlmklib
OCAMLLEX = ocamllex
OCAMLYACC = ocamlyacc
OCAMLDEP = ${OCAMLFIND} ocamldep
OCAMLMKTOP = ocamlmktop
OCAMLJAVA = ocamljava -java-extensions

JAVA=java
JAVAC=javac

BINDIR = $(shell opam config var bin)
LIBDIR = $(shell opam config var lib)

OJACARE = ${BINDIR}/ojacare
