
### Specific to your application

MAIN      := main_point
IDL       := p
MLINCDIRS :=
MODULES   :=
LIBRARIES :=
CLASSES   := mypack/Point mypack/Colored mypack/ColoredPoint mypack/Cloud
CBCLASSES := mypack/ColoredPoint

EXTRA_JAR_CLASSES := ${CLASSES}

include $(shell ocamlfind query ojacare)/Makefile.ojacare
