# Adjust to your installation
OCAMLC = ocamlc
OCAMLOPT = ocamlopt.opt 
OCAMLMKLIB = ocamlmklib
OCAMLLEX = ocamllex
OCAMLYACC = ocamlyacc
OCAMLDEP = ocamldep 
OCAMLMKTOP = ocamlmktop

OJACARE = ojacare
OJACAREDIR = $(shell ocamlfind printconf destdir)/ojacare

CAMLJAVADIR = $(shell ocamlfind printconf destdir)/camljava