
### Specific to your application

MAIN      := main_point
IDL       := p
MLINCDIRS :=
MODULES   :=
LIBRARIES :=
PACK      := mypack
CLASSES   := Point Colored ColoredPoint Cloud
CBCLASSES := ColoredPoint

include $(shell ocamlfind query ojacare)/Makefile.ojacare
