#	$Id: Makefile,v 1.2 2004/03/28 02:45:09 henry Exp $

include ../Makefile.config

# Nom de l'éxécutable
EXEC = awt

# Liste des fichiers IDL
IDL       = awt

# Liste des répertoires contenant les modules et bibliotèques Caml utilisées
MLINCDIRS = 

# Liste des modules Caml 
MODULES   = 

# Liste des bibliothèques Caml à inclure à l'édition de lien
LIBRARIES = 

# Liste des bibliothèques C à inclure à l'édition de lien
CLIBS     = 

# Liste des classes Java à compiler
CLASS     = 

# Liste des classes Java ayant l'attribut callback 
CBCLASS   = java/awt/event/ActionListener

include $(OJACAREDIR)/Makefile.include