#	$Id: Makefile,v 1.3 2004/03/28 02:45:09 henry Exp $

include ../Makefile.config

MLINCDIRS = 

EXEC      = observer
IDL       = observer
MODULES   = 
LIBRARIES = 
CLIBS     = 
CLASS     = mypack/Data mypack/Observer mypack/Subject mypack/ConcreteSubject \
		mypack/JavaMain mypack/MlMain
CBCLASS   = mypack/Observer mypack/MlMain

include $(OJACAREDIR)/Makefile.include
