
### Specific to your application

MAIN      := formule main_visiteur
IDL       := visiteur
MLINCDIRS :=
MODULES   :=
LIBRARIES :=
PACK      :=
CLASSES   := fr/upmc/infop6/mlo/Formule fr/upmc/infop6/mlo/Visiteur fr/upmc/infop6/mlo/VisiteurTS
CBCLASSES :=

EXTRA_JAR_CLASSES := ${CLASSES}

include $(shell ocamlfind query ojacare)/Makefile.ojacare
