#	$Id: Makefile.config,v 1.2 2004/03/19 20:42:56 henry Exp $

# Adjust to your O'Caml installation 
OCAMLC = ocamlfind ocamlc  $(PACKAGES)
OCAMLOPT = ocamlfind ocamlopt $(PACKAGES)
OCAMLMKLIB = ocamlmklib
OCAMLLEX = ocamllex
OCAMLYACC = ocamlyacc
OCAMLDEP = ocamlfind ocamldep 
OCAMLMKTOP = ocamlmktop

# Adjust to where you want to install O'Jacare
PREFIX = $(shell opam config --switch 4.01.0+ocamljava var prefix)
BINDIR = $(shell opam config --switch 4.01.0+ocamljava var bin)
LIBDIR = $(shell opam config --switch 4.01.0+ocamljava var lib)/ojacare
