#	$Id: Makefile.config,v 1.2 2004/03/19 20:42:56 henry Exp $

PACKAGES = 

# Adjust to your O'Caml installation 
OCAMLC = ocamlfind ocamlc -annot $(PACKAGES)
OCAMLOPT = ocamlfind ocamlopt -annot $(PACKAGES)
OCAMLMKLIB = ocamlmklib
OCAMLLEX = ocamllex
OCAMLYACC = ocamlyacc
OCAMLDEP = ocamlfind ocamldep 
OCAMLMKTOP = ocamlmktop

# Adjust to where you want to install O'Jacare
PREFIX = $(shell opam config --switch 4.01.0 var prefix)
BINDIR = $(PREFIX)/bin
LIBDIR = $(shell ocamlfind printconf destdir)/ojacare
