#	$Id: Makefile.config,v 1.2 2004/03/19 20:42:56 henry Exp $


PACKAGES = -package camljava

# Adjust to your O'Caml installation 
OCAMLC = ocamlfind ocamlc -annot $(PACKAGES)
OCAMLOPT = ocamlfind ocamlopt -annot $(PACKAGES)
OCAMLMKLIB = ocamlmklib
OCAMLLEX = ocamllex
OCAMLYACC = ocamlyacc
OCAMLDEP = ocamlfind ocamldep 
OCAMLMKTOP = ocamlmktop


# Adjust to your 'camljava' installation
CAMLJAVADIR = $(shell ocamlfind printconf destdir)/camljava


# Adjust to where you want to install O'Jacare
PREFIX = /usr/local
BINDIR = $(PREFIX)/bin
LIBDIR = $(shell ocamlfind printconf destdir)/ojacare
