#	$Id: Makefile,v 1.5 2004/03/28 02:45:09 henry Exp $

include ../Makefile.config

MLINCDIRS = 

EXEC      = rectangle
IDL       = r
MODULES   = 
LIBRARIES = 
CLIBS     = 
CLASS     = mypack/Point mypack/RectangleGr mypack/RectangleGeo
CBCLASS   = 

include $(OJACAREDIR)/Makefile.include
