package mypack;

class Point {
 
  int x;
  int y; 
  
  [name default_point] <init> ();
  [name point] <init> (int,int);
  
  void moveto(int,int);
  void rmoveto(int,int);
  string toString();
  void display();
  double distance();
  boolean eq(Point);

  static void main(string [] arg);

}
